### ISSUE TITLE
No such file or directory: './datasets/horse_train.pt'

### ISSUE THREAD

**Issue by RL0303** [ColumbiaDVMM/AutoGAN#11]
Hi, I got the error when I try to train the classifier
$ python run_training.py --dataset=CycleGAN --feature=fft --gpu-id=0

Test Parameter:  --feature=fft 
python GAN_Detection_Train.py --training-set horse --model=resnet --test-set=transposed_conv --data_augment                        --batch-size=16 --test-batch-size=16  --feature=fft  --gpu-id 0 --model-dir ./model_resnet/  --log-dir ./resnet_log/ --enable-logging=False --epochs 20 
Wait for process end

/home/lab/miniconda3/envs/AutoGAN/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/home/lab/miniconda3/envs/AutoGAN/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

# Caching data ./datasets/horse_train.pt
Traceback (most recent call last):
  File "GAN_Detection_Train.py", line 434, in <module>
    train_loader, test_loaders = create_loaders()
  File "GAN_Detection_Train.py", line 261, in create_loaders
    GANDataset(train=True,
  File "GAN_Detection_Train.py", line 169, in __init__
    super(GANDataset, self).__init__(train=train, *arg, **kw)
  File "/home/lab/Downloads/AutoGAN/code/cycleGAN_dataset.py", line 68, in __init__
    self.cache_data(data_file, name, check_cached)
  File "/home/lab/Downloads/AutoGAN/code/cycleGAN_dataset.py", line 103, in cache_data
    with open(data_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './datasets/horse_train.pt'

Thanks for your work,
Robert

**Comment by RL0303** [comment]
I found the solution is to fix the path in file (GAN_Detection_Train.py).

 i.e. '--dataroot', type=str,
                    # default='./datasets/',
                    default='../autogan/datasets/'
